--всі запити клієнтів, через форму 
SELECT CUSNAME, CUSPHONE, MESSDESCRIPTION
FROM CLIENT, SENDMESSADGE
WHERE CUSID=CLIENT.ID;

--всі бронювання за один день
SELECT CUSNAME, CUSPHONE, ROOMNAME, DATARENT,TIMESTARTRENT, TIMEENDRENT
FROM CLIENT, ROOM, ORD
WHERE CUSID=CLIENT.ID AND ROOMID=ROOM.ID AND DATARENT='2023-05-24';

--всі бронювання від найпершого в порядку зростання
SELECT CUSNAME, CUSPHONE, ROOMNAME, DATARENT,TIMESTARTRENT, TIMEENDRENT
FROM CLIENT, ROOM, ORD
WHERE CUSID=CLIENT.ID AND ROOMID=ROOM.ID
ORDER BY DATARENT ASC;

--всі бронювання в студії №3
SELECT CUSNAME, CUSPHONE, ROOMNAME, DATARENT,TIMESTARTRENT, TIMEENDRENT
FROM CLIENT, ROOM, ORD
WHERE CUSID=CLIENT.ID AND ROOMID=ROOM.ID AND ROOMNAME='студія 3';

--перегляд інформації про локації
SELECT ROOMNAME, ROOMDESCRIPTION, DATARENT, TIMESTARTRENT, TIMEENDRENT
FROM ORD, ROOM;

--яка студія для оренди найпопулярніша--
SELECT TOP 1 ROOMID, COUNT(*) AS RENTAL_COUNT
FROM ORD
GROUP BY ROOMID
ORDER BY RENTAL_COUNT DESC;


--загальна кількість бронювань за весь період
SELECT COUNT(ID) FROM ORD;

--загальна кількість бронювань зроблених раніше 2023-05-24
SELECT COUNT(ID) FROM ORD
WHERE DATARENT <='2023-05-24';

--інформація про бронювання, які зроблені раніше 2023-05-24
SELECT * FROM ORD
WHERE DATARENT <='2023-05-24';

--інформація про клієнта, який зробив більше ніж 2 бронювання
SELECT C.CUSNAME, S.ROOMNAME, B.DATARENT
FROM CLIENT C
JOIN ORD B ON C.ID=B.CUSID
JOIN ROOM S ON B.ROOMID=S.ID
WHERE C.ID IN(
SELECT CUSID
FROM ORD
GROUP BY CUSID
HAVING COUNT(*)>2);


--кількість бронювань студії №1
SELECT COUNT (*) AS ROOM_COUNT
FROM ORD
WHERE ROOMID = 1;


--статистика бронювань різних студій--
SELECT S.ROOMNAME, COUNT(*) AS КІЛЬКІСТЬ_БРОНЮВАНЬ
FROM ORD B
JOIN ROOM S ON B.ROOMID=S.ID
GROUP BY S.ROOMNAME;


--імя та телефон клієнтів, які бронювали студію 2
SELECT C.CUSNAME, C.CUSPHONE, B.DATARENT, B.TIMEENDRENT, B.TIMEENDRENT, S.ROOMNAME
FROM ORD B
JOIN ROOM S ON B.ROOMID=S.ID
JOIN CLIENT C ON B.CUSID= C.ID
WHERE B.ROOMID = 2;


--імя клієнта, який бронював на один і той самий час різні студії
SELECT DISTINCT C.CUSNAME, C.CUSPHONE, C.ID
FROM CLIENT C
INNER JOIN ORD B1 ON C.ID=B1.CUSID
INNER JOIN ORD B2 ON C.ID=B2.CUSID
WHERE B1.ROOMID<>B2.ROOMID AND B1.TIMESTARTRENT=B2.TIMESTARTRENT;