--всі запити клієнтів, через форму 
SELECT CUSNAME, CUSPHONE, MESSDESCRIPTION
FROM CLIENT, SENDMESSADGE
WHERE CUSID=CLIENT.ID;

--всі бронювання від найпершого в порядку зростання
SELECT CUSNAME, CUSPHONE, ROOMNAME, DATARENT,TIMESTARTRENT, TIMEENDRENT
FROM CLIENT, ROOM, ORD
WHERE CUSID=CLIENT.ID AND ROOMID=ROOM.ID
ORDER BY DATARENT ASC;

--всі бронювання за один день
SELECT CUSNAME, CUSPHONE, ROOMNAME, DATARENT,TIMESTARTRENT, TIMEENDRENT
FROM CLIENT, ROOM, ORD
WHERE CUSID=CLIENT.ID AND ROOMID=ROOM.ID AND DATARENT='2023-05-24';

--всі бронювання в студії №3
SELECT CUSNAME, CUSPHONE, ROOMNAME, DATARENT,TIMESTARTRENT, TIMEENDRENT
FROM CLIENT, ROOM, ORD
WHERE CUSID=CLIENT.ID AND ROOMID=ROOM.ID AND ROOMNAME='студія 3';

--вся інформація про клієнтів жіночої статі
SELECT *
FROM CLIENT
WHERE CUSGENDER ='ж';

--кількість клієнтів жіночої статі
SELECT COUNT(CUSGENDER) FROM CLIENT
WHERE CUSGENDER ='ж';

--загальна кількість бронювань за весь період
SELECT COUNT(ID) FROM ORD;

--загальна кількість бронювань зроблених раніше 2023-05-24
SELECT COUNT(ID) FROM ORD
WHERE DATARENT <='2023-05-24';

--інформація про бронювання, які зроблені раніше 2023-05-24
SELECT * FROM ORD
WHERE DATARENT <='2023-05-24';

--номер клієнта, який зробив більше ніж 1 бронювання
SELECT CUSID FROM ORD
GROUP BY CUSID
HAVING COUNT(*) > 1;


--кількість бронювань студії №1
SELECT COUNT (*) AS ROOM_COUNT
FROM ORD
WHERE ROOMID = 1;

--статистика бронювань різних студій--
SELECT ROOMID,COUNT(*) AS BOOKINGS_COUNT
FROM ORD
GROUP BY ROOMID;

--яка студія для оренди найпопулярніша--
SELECT TOP 1 ROOMID, COUNT(*) AS RENTAL_COUNT
FROM ORD
GROUP BY ROOMID
ORDER BY RENTAL_COUNT DESC;

--імя та телефон клієнтів, які бронювали студію 3
SELECT CUSNAME, CUSPHONE
FROM CLIENT
INNER JOIN ORD ON CLIENT.ID=ORD.CUSID
WHERE ORD.ROOMID=3;

--імя клієнта, який бронював на один і той самий час різні студії
SELECT DISTINCT C.CUSNAME, C.CUSPHONE, C.ID
FROM CLIENT C
INNER JOIN ORD B1 ON C.ID=B1.CUSID
INNER JOIN ORD B2 ON C.ID=B2.CUSID
WHERE B1.ROOMID<>B2.ROOMID AND B1.TIMESTARTRENT=B2.TIMESTARTRENT;






